# conversational_asl.py

CONVERSATIONAL_ASL = [
    # Greetings
    ("HELLO", "Hello"),
    ("SEE YOU LATER", "See you later"),
    ("NICE MEET YOU", "Nice to meet you"),
    ("HOW YOU", "How are you?"),
    ("FINE THANK YOU", "I'm fine, thank you"),
    ("GOOD MORNING", "Good morning"),
    ("WHAT UP?", "What's up?"),
    ("GOOD SEE YOU", "Good to see you"),
    ("LONG TIME NO SEE", "Long time no see"),
    ("WHERE YOU BEEN?", "Where have you been?"),
    ("TAKE CARE", "Take care"),
    ("TALK LATER", "Talk to you later"),
    ("HAVE GOOD DAY", "Have a good day"),
    
    # Introductions
    ("NAME YOU?", "What is your name?"),
    ("MY NAME J-O-H-N", "My name is John"),
    ("NICE MEET YOU", "Nice to meet you"),
    ("WHERE YOU FROM", "Where are you from?"),
    ("I FROM CALIFORNIA", "I'm from California"),
    ("I LIVE NEW-YORK", "I live in New York"),
    ("WHAT YOU DO?", "What do you do?"),
    ("I STUDENT", "I'm a student"),
    ("I WORK HOSPITAL", "I work at a hospital"),
    ("YOU DEAF?", "Are you deaf?"),
    ("YES I DEAF", "Yes, I'm deaf"),
    ("YOU KNOW SIGN?", "Do you know sign language?"),
    ("LITTLE-BIT", "A little bit"),
    ("HOW-LONG YOU SIGN", "How long have you been signing?"),
    ("TWO YEAR", "Two years"),
    ("YOU GOOD SIGNER", "You're a good signer"),
    
    # Daily Activities
    ("I WAKE-UP", "I wake up"),
    ("I EAT BREAKFAST", "I eat breakfast"),
    ("I GO WORK", "I go to work"),
    ("I COME HOME", "I come home"),
    ("I COOK DINNER", "I cook dinner"),
    ("I WATCH TV", "I watch TV"),
    ("I READ BOOK", "I read a book"),
    ("I GO SLEEP", "I go to sleep"),
    ("I BRUSH TEETH", "I brush my teeth"),
    ("I TAKE SHOWER", "I take a shower"),
    ("I DRIVE CAR", "I drive my car"),
    ("I RIDE BUS", "I ride the bus"),
    ("I EXERCISE", "I exercise"),
    ("I CLEAN HOUSE", "I clean the house"),
    ("I RELAX", "I relax"),
    ("I CALL FRIEND", "I call a friend"),
    ("I BROWSE INTERNET", "I browse the internet"),
    ("I PLAY GAME", "I play games"),
    ("I LISTEN MUSIC", "I listen to music"),
    ("I MEET FRIEND", "I meet a friend"),
    ("I GO MOVIE", "I go to the movies"),
    ("I WORK LATE", "I work late"),
    
    # Questions (30)
    ("WHERE YOU LIVE?", "Where do you live?"),
    ("AGE YOU?", "How old are you?"),
    ("TIME?", "What time is it?"),
    ("WHERE BATHROOM?", "Where is the bathroom?"),
    ("HOW MUCH COST?", "How much does it cost?"),
    ("YOU UNDERSTAND?", "Do you understand?"),
    ("YOU MARRIED?", "Are you married?"),
    ("YOU HAVE CHILDREN?", "Do you have children?"),
    ("WHAT YOU WANT?", "What do you want?"),
    ("WHAT YOU NEED?", "What do you need?"),
    ("WHAT YOU THINK?", "What do you think?"),
    ("YOU HUNGRY?", "Are you hungry?"),
    ("YOU TIRED?", "Are you tired?"),
    ("YOU BUSY?", "Are you busy?"),
    ("YOU FREE TOMORROW?", "Are you free tomorrow?"),
    ("YOU LIKE?", "Do you like it?"),
    ("YOU WANT COFFEE?", "Do you want coffee?"),
    ("YOU NEED HELP?", "Do you need help?"),
    ("CAN YOU HELP ME?", "Can you help me?"),
    ("WHAT HAPPEN?", "What happened?"),
    ("WHERE YOU GO?", "Where are you going?"),
    ("WHEN YOU LEAVE?", "When are you leaving?"),
    ("HOW-LONG YOU STAY?", "How long are you staying?"),
    
    # Food & Drink (25)
    ("I HUNGRY", "I'm hungry"),
    ("I THIRSTY", "I'm thirsty"),
    ("I WANT WATER", "I want water"),
    ("I WANT COFFEE", "I want coffee"),
    ("I LIKE PIZZA", "I like pizza"),
    ("I NOT LIKE VEGETABLES", "I don't like vegetables"),
    ("FOOD DELICIOUS", "The food is delicious"),
    ("FOOD BAD", "The food is bad"),
    ("I FULL", "I'm full"),
    ("I FINISH EAT", "I finished eating"),
    ("YOU WANT MORE?", "Do you want more?"),
    ("NO THANK YOU", "No, thank you"),
    ("YES PLEASE", "Yes, please"),
    ("WHAT YOU WANT EAT?", "What do you want to eat?"),
    ("WHAT YOU WANT DRINK?", "What do you want to drink?"),
    ("I WANT SALAD", "I want a salad"),
    ("I WANT SANDWICH", "I want a sandwich"),
    ("I ALLERGIC", "I'm allergic"),
    ("I VEGETARIAN", "I'm vegetarian"),
    ("I PAY", "I'll pay"),
    ("SPLIT BILL", "Let's split the bill"),
    ("THANK YOU FOR MEAL", "Thank you for the meal"),
    ("YOU WELCOME", "You're welcome"),
    
    # Feelings & Emotions (25)
    ("I HAPPY", "I'm happy"),
    ("I SAD", "I'm sad"),
    ("I PROUD", "I'm proud"),
    ("I EMBARRASSED", "I'm embarrassed"),
    ("I DISAPPOINTED", "I'm disappointed"),
    ("I SICK", "I'm sick"),
    ("I FEEL BETTER", "I feel better"),
    ("I FEEL WORSE", "I feel worse"),
    ("I FINE", "I'm fine"),
    ("I OK", "I'm okay"),
    ("I NOT OK", "I'm not okay"),
    ("I STRESSED", "I'm stressed"),
    ("I RELAXED", "I'm relaxed"),
    ("I LOVE YOU", "I love you"),
    ("I MISS YOU", "I miss you"),
    
    # Negation (20)
    ("I NOT WANT", "I don't want"),
    ("I NOT UNDERSTAND", "I don't understand"),
    ("I CANNOT", "I can't"),
    ("I NOT READY", "I'm not ready"),
    ("NOT TRUE", "That's not true"),
    ("NOT POSSIBLE", "That's not possible"),
    ("NOT MY FAULT", "That's not my fault"),
    ("I DISAGREE", "I disagree"),
    ("I NOT SURE", "I'm not sure"),
    
    # Time & Tense (30)
    ("YESTERDAY I GO SCHOOL", "I went to school yesterday"),
    ("TODAY I WORK", "I'm working today"),
    ("TOMORROW I REST", "I will rest tomorrow"),
    ("LAST WEEK I VISIT FAMILY", "I visited my family last week"),
    ("NEXT WEEK I HAVE MEETING", "I have a meeting next week"),
    ("NOW I STUDY", "I'm studying now"),
    ("LATER I CALL YOU", "I'll call you later"),
    ("PAST I LIVE TEXAS", "I used to live in Texas"),
    ("FUTURE I TRAVEL EUROPE", "I will travel to Europe"),
    ("MONDAY I BUSY", "I'm busy on Monday"),
    ("FRIDAY I FREE", "I'm free on Friday"),
    
    # Family (20)
    ("MY MOTHER TEACHER", "My mother is a teacher"),
    ("MY FATHER DOCTOR", "My father is a doctor"),
    ("I HAVE TWO BROTHER", "I have two brothers"),
    ("I HAVE ONE SISTER", "I have one sister"),
    ("MY SISTER MARRIED", "My sister is married"),
    ("MY FAMILY LIVE CALIFORNIA", "My family lives in California"),
    ("I MISS MY FAMILY", "I miss my family"),
    ("MY SON STUDENT", "My son is a student"),
    ("MY DAUGHTER WORK HOSPITAL", "My daughter works at a hospital"),
    
    # Health (20)
    ("I SICK", "I'm sick"),
    ("I FEEL BETTER", "I feel better"),
    ("I FEEL WORSE", "I feel worse"),
    ("MY HEAD HURT", "My head hurts"),
    ("MY STOMACH HURT", "My stomach hurts"),
    ("MY BACK HURT", "My back hurts"),
    ("MY THROAT HURT", "My throat hurts"),
    ("I HAVE COLD", "I have a cold"),
    ("I HAVE FLU", "I have the flu"),
    ("I HAVE FEVER", "I have a fever"),
    ("I NEED DOCTOR", "I need a doctor"),
    ("I TIRED", "I'm tired"),
    ("YOU OK", "Are you okay?"),
    ("TAKE CARE", "Take care"),
    ("FEEL BETTER", "Feel better"),
    
    #ASL book
    ("HE MOVIE FINISH SEE, NOT-YET.", "He hasn't finished watching the movie yet."),
    ("HE MOVIE FINISH SEE", "He saw the movie"),
    ("ME WILL SEND-you LETTER", "I will send you a letter"),
    ("me-MEET-you WILL, TOMORROW ME PROMISE.", "I promise I will meet you tomorrow."),
    ("PHONE HOME TWICE WEEK, ME WILL. ", "I will phone home twice a week."),
    ("YOU EAT FINISH YOU?", "Have you finished eating?"),
    ("YOU EXERCISE WANT?", "Do you want to exercise?"),
    ("SHE WORK HERE, HOW LONG?", "How long has she worked here?"),
    ("CITY DESTROY BUILDING, WHY?", "Why did the city destroy the building?"),
    ("SUPPOSE SHE SEE ME, ME HAVE-TO LEAVE.", "I will have to leave if she sees me."),
    ("SUPPOSE TONIGHT SNOW, TOMORROW YOU CANCEL SCHOOL. ", "If it snows tonight, then you will cancel school tomorrow."),
    ("SUPPOSE HE SHOW-UP, DO-what YOU?", "If he shows up, what will you do?"),
    ("I-F SHE CAN'T COME, YOU LOSE CONTRACT. ", "If she can't come, you will lose the contract."),
    (" I-F YOU WIN GAME, YOUR TEAM CHAMPION.", "If you win the game, your team will be champion."),
    ("ME NOT WATCH FOOTBALL GAME. ME NOT CARE FOOTBALL.", "I don't watch football. I don't care about football."),
    ("ME CHEAT, NEVER.", "I never cheat."),
    ("ME NAME T-I-N-A. NAME YOU?", "My name is Tina. What is your name?"),
    ("NICE me-MEET-you", "Nice to meet you"),

    ("BOB KISS KATE", "Bob kisses Kate"),
    ("PICNIC FOOD BRING, WHAT YOU?", "What food are you bringing to the picnic?"),
    ("HE BORN, WHEN HE?", "When was he born?"),
    ("YESTERDAY FIX FENCE, HOW YOU?", "How did you fix the fence yesterday?"),
    ("you-PICK-ON-me, WHY YOU?", "Why arre you picking on me?"),

    ("CAT BLACK TREE CLIMB, YOUR?", "Is the black cat climbing the tree yours?"),
    ("CLEAN DISHES WASH CLOTHES, HE?", "Will he clean the dishes and wash the clothes?"),

    ("LAST NIGHT, SUNSET BEAUTIFUL.", "The sunset was beautiful last night"),
    ("ME YESTERDAY, STAY HOME", "I stayed home yesterday"),
    ("LAST NIGHT, GAME SEE FINISH YOU?", "Did you see the game last night?"),
    ("YESTERDAY, YOU HOME ARRIVE, TIME?", "What time did you arrive home yesterday?"),

    ("MY CLASS TITLE, COMPUTER SCIENCE", "The title of my class is Computer Science"),
    ("WOMAN THERE, SHE INTERPRETER.", "That woman is an interpreter."),
    ("ASL PRACTICE, ME MUST?", "Must I practice ASL?"),
    ("HE CLASS SHOW-UP, NOT-YET.", "He hasn't shown up to class yet."),
    ("SIGN, SHE SKILL.", "She is skilled at signing."),

    ("YOUR ROOM, SMALL LARGE WHICH?", "Is your room small or large?"),
    ("MY ROOM, LARGE.", "My room is large."),
    ("YOUR ASL COURSE, FASCINATING DULL WHICH?", "Is your ASL course fascinating or dull?"),
    ("YES, HE ENGINEER.", "Yes, he is an engineer."),
    ("YESTERDAY, DO-what YOU?", "What did you do yesterday?"),
    ("SUNDAY ACCOMPANY-me MOVIE WANT YOU?", "Do you want to come with me to the movies on Sunday?"),
    ("NEXT-WEEK ME CAN'T. IN-THREE-WEEKS MONDAY?", "I can't next week. Can we do Monday in three weeks?"),

    ("BASEBALL ME ENJOY, NOT. ME DECLINE.", "I don't enjoy baseball. I decline."),
    ("TICKETS SELL, YOU CAN.", "You can sell the tickets."),
    ("FINE. TONIGHT, RESTAURANT GO OKAY?", "Fine. Is it okay if we go to a restaurant tonight?"),
    ("MYSELF, RESTAURANT GO?", "Go to a restaurant by myself?"),

    ("YOU GET-WELL QUICK, ME HOPE.", "I hope you get well quick."),
    ("YOUR ASL CLASS END WHEN?", "When does your ASL class end?"),
    ("OKAY. me-MEET-you, TIME EIGHT", "Okay. Let's meet at 8 o'clock."),
    ("you-MEET-me WHERE?", "Where will you meet me?"),
    ("me-MEET-you HERE.", "Let's meet here."),
    ("TIME AGAIN PLEASE?", "Can you say the time again, please?"),
    ("YOU MINOR WHAT?", "What is your minor?"),
    ("ME FEEL DEPRESSED", "I feel depressed"),
    ("ME PLAN STUDY MATH TODAY.", "I plan to study math today."),

    ("YOU LIKE MUSIC WHAT-KIND?", "What kind of music do you like?"),
    ("YOU FAVORITE MOVIE WHAT?", "What is your favorite movie?"),
    ("HARD CHOOSE, MANY GOOD MOVIE.", "It's hard to choose, there are many good movies."),
    ("PAST ME LIVE OTTAWA, NOW ME LIVE HAMILTON.", "I used to live in Ottawa, but now I live in Hamilton."),
    ("TOMORROW ME GO CLASS EARLY.", "Tomorrow I will go to class early."),
    ("BEFORE ME NOT-LIKE COFFEE, NOW LOVE.", "I used to not like coffee, but now I love it."),
    ("LAST-YEAR ME START LEARN SIGN.", "I started learning sign language last year."),

    ("ME PHONE BATTERY DIE, THAT-WHY ME NOT REPLY.", "My phone battery died, that's why I didn't reply."),
    ("OH-I-SEE, ME THINK MAYBE YOU FORGET-ME.", "Oh, I see. I think maybe you forgot about me."),
    ("ME GO STORE, YOU NEED ANYTHING?", "I'm going to the store, do you need anything?"),
    ("THAT HAPPEN ALL-THE-TIME.", "That happens all the time."),
    ("COFFEE, ME PREFER ICED.", "I prefer iced coffee."),
    ("THAT MOVIE, ME WATCH ALREADY.", "I've already watched that movie."),
    ("YOUR FRIEND, ME MEET BEFORE THINK-SO.", "I think I've met your friend before."),
    ("MORNING ME WAKE-UP LATE, RUSH RUSH, ALMOST MISS BUS.", "This morning I woke up late, rushed, and almost missed the bus."),
    ("ME THINK ABOUT CHANGE MAJOR, BUT STILL NOT-SURE.", "I'm thinking about changing my major, but I'm still not sure."),
    ("WHY? CURRENT MAJOR YOU NOT-LIKE?","Why? Do you not like your current major?"),
    ("NOT EXACTLY. ME LIKE, JUST FEEL STRESS A-LOT.", "Not exactly. I like it, I just feel a lot of stress."),
    ("TODAY YOU LOOK TIRED. SLEEP ENOUGH NOT?", "You look tired today. Did you not sleep enough?"),
    ("NOPE. LAST-NIGHT ME KEEP STUDY UNTIL THREE-AM.", "Nope. Last night I kept studying until 3am."),
    ("TODAY WEATHER NICE. YOU WANT WALK PARK?", "The weather is nice today. Do you want to go for a walk in the park?"),
    ("CAN, BUT AFTER ME FINISH WORK FIRST.", "I can, but I need to finish work first."),
    ("FINISH WHAT-TIME?", "What time will you finish?"),
    ("ME THINK THAT GOOD-IDEA.", "I think that's a good idea."),
    ("THAT MOVIE BEGIN SLOW, SO FIRST ME FEEL BORED, BUT THEN ME REALLY ENJOY.", "That movie started slow, so at first I felt bored, but then I really enjoyed it."),
    ("IF YOU DON’T UNDERSTAND FIRST-TIME, DON’T WORRY. ME CAN EXPLAIN AGAIN.", "If you don't understand the first time, don't worry. I can explain it again."),
    ("ME MISS BREAKFAST THIS-MORNING, SO BY NOON ME HUNGRY EXTREMELY.", "I missed breakfast this morning, so by noon I was extremely hungry."),
    ("ME LIKE WORK-ALONE BECAUSE QUIET, FOCUS EASY.", "I like working alone because it's quiet and I can focus easily."),
    ("THAT RESTAURANT FOOD TASTE GOOD TRUE, HOWEVER PRICE TOO-HIGH, SO ME NOT GO OFTEN.", "That restaurant's food tastes really good, however the price is too high, so I don't go there often."),
    ("FIRST ME GO LIBRARY PRINT PAPER, THEN BUY COFFEE.", "First I went to the library to print a paper, then I bought coffee.")
]

# Save to JSON
import json

data = [{"gloss": g, "english": e} for g, e in CONVERSATIONAL_ASL]

with open('conversational_asl.json', 'w') as f:
    json.dump(data, f, indent=2)

print(f"✅ Saved {len(data)} conversational ASL glosses")